core/protocol/urls.py
from django.urls import path
from core.protocol.views.web_views import (
    ProtocolListView, 
    ProtocolCreateView, 
    ProtocolUpdateView, 
    ProtocolDetailView, 
    ProtocolDeleteView
)

app_name = 'protocol'

urlpatterns = [
    path('list/', ProtocolListView.as_view(), name='protocol_list'),
    path('add/', ProtocolCreateView.as_view(), name='protocol_create'),
    path('update/<uuid:pk>/', ProtocolUpdateView.as_view(), name='protocol_update'),
    path('detail/<uuid:pk>/', ProtocolDetailView.as_view(), name='protocol_detail'),
    path('delete/<uuid:pk>/', ProtocolDeleteView.as_view(), name='protocol_delete'),
]

studystb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from studystb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('product/', include('core.product.urls')),
    path('condition/', include('core.condition.urls')),
    path('protocol/', include('core.protocol.urls')),
    # path('company/', include('core.company.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/protocol/models/protocol.py
import uuid
from django.db import models
from django.conf import settings
from core.models import BaseModel
from core.condition.models import Condition


class Protocol(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    code_protocol = models.CharField(max_length=50, unique=True, verbose_name='Código de Protocolo')
    study_type = models.CharField(max_length=100, verbose_name='Tipo de Estudio')
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE, related_name='protocols', verbose_name='Condición')
    objective = models.TextField(verbose_name='Objetivo')
    numbers_batch = models.PositiveIntegerField(verbose_name='Número de Lotes')
    
    prepared_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.PROTECT, 
        related_name='protocols_prepared', 
        verbose_name='Preparado por'
    )
    date_prepared = models.DateField(verbose_name='Fecha de Preparación')
    
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.PROTECT, 
        related_name='protocols_approved', 
        verbose_name='Aprobado por'
    )
    date_approved = models.DateField(verbose_name='Fecha de Aprobación')
    
    enabled_protocol = models.BooleanField(default=True, verbose_name='Protocolo Habilitado')
    version = models.PositiveSmallIntegerField(default=1, verbose_name='Versión')

    class Meta:
        db_table = 'Protocol'
        verbose_name = 'Protocolo'
        verbose_name_plural = 'Protocolos'
        ordering = ['code_protocol', '-version']

    def __str__(self):
        return f"{self.code_protocol} - v{self.version}"

core/protocol/forms.py
from django import forms
from core.protocol.models import Protocol


class ProtocolForm(forms.ModelForm):
    class Meta:
        model = Protocol
        fields = [
            'code_protocol', 
            'study_type', 
            'condition', 
            'objective', 
            'numbers_batch', 
            'prepared_by', 
            'date_prepared', 
            'approved_by', 
            'date_approved', 
            'enabled_protocol', 
            'version'
        ]
        widgets = {
            'code_protocol': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el código'}),
            'study_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el tipo de estudio'}),
            'condition': forms.Select(attrs={'class': 'form-control select2'}),
            'objective': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Ingrese el objetivo'}),
            'numbers_batch': forms.NumberInput(attrs={'class': 'form-control'}),
            'prepared_by': forms.Select(attrs={'class': 'form-control select2'}),
            'date_prepared': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'approved_by': forms.Select(attrs={'class': 'form-control select2'}),
            'date_approved': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'enabled_protocol': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'version': forms.NumberInput(attrs={'class': 'form-control'}),
        }

core/protocol/views/web_views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from core.mixins import ValidatePermissionRequiredMixin
from core.protocol.models import Protocol
from core.protocol.forms import ProtocolForm
from core.protocol.selectors.protocol_selectors import protocol_list_selector, protocol_detail_selector
from core.protocol.services.protocol_services import protocol_create_service, protocol_update_service, protocol_delete_service


class ProtocolListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Protocol
    template_name = 'protocol/list_protocol.html'
    permission_required = 'protocol.view_protocol'

    def get_queryset(self):
        return protocol_list_selector()

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for p in self.get_queryset():
                    data.append({
                        'id': p.id,
                        'code_protocol': p.code_protocol,
                        'study_type': p.study_type,
                        'condition': p.condition.zone_condition,
                        'prepared_by': p.prepared_by.get_full_name(),
                        'date_prepared': p.date_prepared.strftime('%Y-%m-%d'),
                        'enabled_protocol': p.enabled_protocol,
                        'version': p.version,
                    })
                return JsonResponse(data, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Protocolos'
        context['create_url'] = reverse_lazy('protocol:protocol_create')
        context['entity'] = 'Listado de Protocolos'
        context['div'] = '12'
        return context


class ProtocolCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Protocol
    form_class = ProtocolForm
    template_name = 'protocol/create_protocol.html'
    success_url = reverse_lazy('protocol:protocol_list')
    permission_required = 'protocol.add_protocol'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    # Using service for creation
                    protocol_create_service(**form.cleaned_data)
                    messages.success(request, 'Protocolo creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear Protocolo'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        context['entity'] = 'Creación de Protocolo'
        context['div'] = '12'
        return context


class ProtocolUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Protocol
    form_class = ProtocolForm
    template_name = 'protocol/create_protocol.html'
    success_url = reverse_lazy('protocol:protocol_list')
    permission_required = 'protocol.change_protocol'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    # Using service for update
                    protocol_update_service(self.object, **form.cleaned_data)
                    messages.success(request, 'Protocolo editado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Protocolo'
        context['list_url'] = self.success_url
        context['entity'] = 'Edición de Protocolo'
        context['action'] = 'edit'
        context['div'] = '12'
        return context


class ProtocolDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = Protocol
    template_name = 'protocol/detail_protocol.html'
    permission_required = 'protocol.view_protocol'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle del Protocolo'
        context['entity'] = 'Detalle del Protocolo'
        context['list_url'] = reverse_lazy('protocol:protocol_list')
        return context


class ProtocolDeleteView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DeleteView):
    model = Protocol
    success_url = reverse_lazy('protocol:protocol_list')
    permission_required = 'protocol.delete_protocol'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object = self.get_object()
            protocol_delete_service(self.object)
            messages.success(request, 'Protocolo eliminado satisfactoriamente!')
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

core/protocol/templates/protocol/create_protocol.html
{% extends 'form_one.html' %}
<line_number>: 

core/protocol/templates/protocol/detail_protocol.html
{% extends 'body.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ entity }}</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Código de Protocolo</label>
                                <p class="form-control-static mt-0">{{ object.code_protocol }}</p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Tipo de Estudio</label>
                                <p class="form-control-static mt-0">{{ object.study_type }}</p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Condición</label>
                                <p class="form-control-static mt-0">{{ object.condition.zone_condition }} - {{ object.condition.description_condition }}</p>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="form-group">
                                <label class="mb-0">Versión</label>
                                <p class="form-control-static mt-0">{{ object.version }}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Estado</label>
                                <p class="form-control-static mt-0">
                                    {% if object.enabled_protocol %}
                                        <span class="badge badge-success">Habilitado</span>
                                    {% else %}
                                        <span class="badge badge-danger">Inhabilitado</span>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="mb-0">Objetivo</label>
                                <p class="form-control-static mt-0">{{ object.objective }}</p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Preparado por</label>
                                <p class="form-control-static mt-0">{{ object.prepared_by.get_full_name }}</p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Fecha de Preparación</label>
                                <p class="form-control-static mt-0">{{ object.date_prepared|date:"d/m/Y" }}</p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Aprobado por</label>
                                <p class="form-control-static mt-0">{{ object.approved_by.get_full_name }}</p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Fecha de Aprobación</label>
                                <p class="form-control-static mt-0">{{ object.date_approved|date:"d/m/Y" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ list_url }}" class="btn btn-default">
                        <i class="now-ui-icons arrows-1_minimal-left"></i> Volver
                    </a>
                    <a href="{% url 'protocol:protocol_update' object.pk %}" class="btn btn-warning">
                        <i class="now-ui-icons ui-2_settings-90"></i> Editar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/protocol/templates/protocol/list_protocol.html
{% extends 'list_one.html' %} 
{% load static %} 

{% block head_list %}
<script src="{% static 'list_protocol.js' %}"></script>
{% endblock %} 

{% block columns %}
<tr>
  <th class="text-center">Protocolo</th>
  <th class="text-center">Tipo de Estudio</th>
  <th class="text-center">Condición</th>
  <th class="text-center">Preparado por</th>
  <th class="text-center">Fecha Prep.</th>
  <th class="text-center">Estado</th>
  <th class="text-center">v.</th>
  <th class="text-center">Opciones</th>
</tr>
{% endblock %} 

{% block rows %} 
{% endblock %} 

{% block create %}
<a
  href="{{ create_url }}"
  class="btn btn-primary btn-round btn-icon float-end"
  style="margin-left: 10px"
>
  <i class="now-ui-icons ui-1_simple-add"></i>
</a>
{% endblock %} 

{% block javascript %} 
{% endblock %}