core/condition/urls.py
from django.urls import path
from core.condition.views import *

app_name = 'condition'

urlpatterns = [
    path('add/', ConditionCreateView.as_view(), name='condition_create'),
    path('list/', ConditionListView.as_view(), name='condition_list'),
    path('update/<uuid:pk>/', ConditionUpdateView.as_view(), name='condition_update'),
    path('detail/<uuid:pk>/', ConditionDetailView.as_view(), name='condition_detail'),
]

studystb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from studystb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('product/', include('core.product.urls')),
    path('condition/', include('core.condition.urls')),
    path('protocol/', include('core.protocol.urls')),
    # path('company/', include('core.company.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/condition/models.py
import uuid
from core.models import BaseModel
from django.db import models
from crum import get_current_user
from studystb.settings import MEDIA_URL, STATIC_URL


# Productos
class Condition(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    zone_condition = models.CharField(max_length=10, verbose_name='Zona')   
    description_condition = models.CharField(max_length=100, verbose_name='Descripción')     
    study_type = models.CharField(max_length=20, verbose_name='Tipo de estudio')
    temperture_sup = models.SmallIntegerField(verbose_name='Temp. Superior °C')     
    temperture_inf = models.SmallIntegerField(verbose_name='Temp. Inferior °C')
    percent_humidity_sup = models.SmallIntegerField(verbose_name='% de HR superior')     
    percent_humidity_inf = models.SmallIntegerField(verbose_name='% de HR inferior')  
    period_minimum_time = models.SmallIntegerField(verbose_name='Meses del Estudio')
    detail_condition = models.TextField(verbose_name='Detalle de la condición', null=True, blank=True)   
    version = models.PositiveSmallIntegerField(default=1)
    condition_enabled = models.BooleanField(default=True, verbose_name='Activo')
    
    def __str__(self):
        return self.zone_condition
    
    class Meta:
        db_table = 'Condition'
        verbose_name = 'Condition'
        verbose_name_plural = 'Conditions'
        ordering = ['zone_condition', '-version']

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        user = get_current_user()
        if user:
            if not self.user_creation:
                self.user_creation = user
            else:
                self.user_updated = user        
        return super(Condition, self).save(*args, **kwargs)

core/condition/forms.py
from django.forms import ModelForm, TextInput, Textarea, NumberInput, Select
from core.condition.models import Condition
from django.core.exceptions import ValidationError

ZONE = [
    ('Zona I', 'Zona I'), ('Zona II', 'Zona II'), ('Zona III', 'Zona III'), ('Zona IVa', 'Zona IVa'), ('Zona IVb', 'Zona IVb')
]

STUDY_TYPE = [
    ('Acelerado', 'Acelerado'), ('Natural', 'Natural'), ('Intermedio', 'Intermedio')
]

TIME_STUDY = [
    ('3', '3 Meses'), ('6', '6 Meses'), ('12', '12 Meses'), ('24', '24 Meses'), ('36', '36 Meses'), ('60', '60 Meses')
]

class ConditionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

        col_classes = {
            'zone_condition': 'col-md-2',        
            'study_type': 'col-md-2',
            'temperture_sup': 'col-md-2',
            'temperture_inf': 'col-md-2',
            'percent_humidity_sup': 'col-md-2',
            'percent_humidity_inf': 'col-md-2',
            'period_minimum_time': 'col-md-2',
            'detail_condition': 'col-md-6',
            'description_condition': 'col-md-4',         
        }

        for field_name, field in self.fields.items():
            field.col_class = col_classes.get(field_name, 'col-md-3')      

    class Meta:
        model = Condition
        fields = [
            'zone_condition',
            'description_condition',
            'study_type',
            'temperture_inf',
            'temperture_sup',
            'percent_humidity_inf',
            'percent_humidity_sup',
            'period_minimum_time',
            'detail_condition',
        ]
        widgets = {
            'zone_condition': Select(attrs={'class': 'form-control', 'required': True}, choices=ZONE),
            'description_condition': TextInput(attrs={'class': 'form-control', 'required': True}),
            'study_type': Select(attrs={'class': 'form-control', 'required': True}, choices=STUDY_TYPE),
            'temperture_sup': TextInput(attrs={'class': 'form-control', 'required': True}),
            'temperture_inf': TextInput(attrs={'class': 'form-control', 'required': True}),
            'percent_humidity_sup': TextInput(attrs={'class': 'form-control', 'required': True}),
            'percent_humidity_inf': TextInput(attrs={'class': 'form-control', 'required': True}),
            'period_minimum_time': Select(attrs={'class': 'form-control', 'required': True}, choices=TIME_STUDY),
            'detail_condition': TextInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned = super().clean()
        zone = self.cleaned_data.get('zone_condition')
        # Here we could add validation if needed, similar to ProductForm
        return cleaned


class ConditionUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

        col_classes = {
            'zone_condition': 'col-md-2',        
            'study_type': 'col-md-2',
            'temperture_inf': 'col-md-2',
            'temperture_sup': 'col-md-2',
            'percent_humidity_inf': 'col-md-2',
            'percent_humidity_sup': 'col-md-2',
            'period_minimum_time': 'col-md-2',
            'detail_condition': 'col-md-6',
            'description_condition': 'col-md-4',         
        }

        for field_name, field in self.fields.items():
            field.col_class = col_classes.get(field_name, 'col-md-3')      

    class Meta:
        model = Condition
        fields = [
            'zone_condition',
            'description_condition',
            'study_type',
            'temperture_inf',
            'temperture_sup',
            'percent_humidity_inf',
            'percent_humidity_sup',
            'period_minimum_time',
            'detail_condition',
        ]
        widgets = {
            'zone_condition': Select(attrs={'class': 'form-control', 'required': True}, choices=ZONE),
            'description_condition': TextInput(attrs={'class': 'form-control', 'required': True}),
            'study_type': Select(attrs={'class': 'form-control', 'required': True}, choices=STUDY_TYPE),
            'temperture_sup': TextInput(attrs={'class': 'form-control', 'required': True}),
            'temperture_inf': TextInput(attrs={'class': 'form-control', 'required': True}),
            'percent_humidity_sup': TextInput(attrs={'class': 'form-control', 'required': True}),
            'percent_humidity_inf': TextInput(attrs={'class': 'form-control', 'required': True}),
            'period_minimum_time': Select(attrs={'class': 'form-control', 'required': True}, choices=TIME_STUDY),
            'detail_condition': TextInput(attrs={'class': 'form-control'}),
        }

core/condition/views.py
from core.condition.models import Condition
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, CreateView, DetailView
from core.mixins import ValidatePermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from core.condition.forms import ConditionForm, ConditionUpdateForm


# Creación de Condición
class ConditionCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Condition
    form_class = ConditionForm
    template_name = 'condition/create_condition.html'
    success_url = reverse_lazy('condition:condition_list')
    permission_required = 'condition.add_condition'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Condición creada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Condiciones de Estudios de Estabilidad'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        context['entity'] = 'Creación de Condiciones de Estudios de Estabilidad'
        context['div'] = '12'
        context['number_column'] = 5
        return context


# Edición de Condición
class ConditionUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Condition
    form_class = ConditionUpdateForm
    template_name = 'condition/create_condition.html'
    success_url = reverse_lazy('condition:condition_list')
    permission_required = 'condition.change_condition'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Condición editada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Condiciones de Estudios de Estabilidad'
        context['list_url'] = self.success_url
        context['entity'] = 'Edición de Condiciones de Estudios de Estabilidad'
        context['action'] = 'edit'
        context['div'] = '12'
        context['number_column'] = 5
        return context


# Detalle de Condición
class ConditionDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = Condition
    template_name = 'condition/detail_condition.html'
    permission_required = 'condition.view_condition'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(ConditionDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle de Condición'
        context['entity'] = 'Detalle de Condición'
        context['list_url'] = reverse_lazy('condition:condition_list')
        return context


# Listado de Condiciones
class ConditionListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Condition
    template_name = 'condition/list_condition.html'
    permission_required = 'condition.view_condition'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    @staticmethod
    def post(request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                conditions = list(Condition.objects.values(
                    'id',
                    'zone_condition',
                    'description_condition',
                    'study_type',
                    'temperture_inf',
                    'temperture_sup',
                    'percent_humidity_inf',
                    'percent_humidity_sup',
                    'period_minimum_time',
                    'condition_enabled',
                    'version'
                ).order_by('zone_condition', 'study_type', '-version'))
                return JsonResponse(conditions, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Condiciones de Estudios de Estabilidad'
        context['create_url'] = reverse_lazy('condition:condition_create')
        context['entity'] = 'Condiciones de Estudios de Estabilidad'
        context['div'] = '12'
        return context

core/condition/templates/condition/create_condition.html
{% extends 'form_one.html' %}

core/condition/templates/condition/detail_condition.html
{% extends 'body.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ entity }}</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Zona</label>
                                <p class="form-control-static mt-0">{{ object.zone_condition }}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Descripción</label>
                                <p class="form-control-static mt-0">{{ object.description_condition }}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Tipo de Estudio</label>
                                <p class="form-control-static mt-0">{{ object.study_type }}</p>
                            </div>
                        </div>
                         <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Meses de Estudio</label>
                                <p class="form-control-static mt-0">{{ object.period_minimum_time }}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Versión</label>
                                <p class="form-control-static mt-0">{{ object.version }}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="mb-0">Estado</label>
                                <p class="form-control-static mt-0">
                                    {% if object.condition_enabled %}
                                        <span class="badge badge-success">Activo</span>
                                    {% else %}
                                        <span class="badge badge-danger">Inactivo</span>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Rango de Temperatura</label>
                                <p class="form-control-static mt-0">
                                    {{ object.temperture_inf }} - {{ object.temperture_sup }} °C
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="mb-0">Rango de Humedad Relativa</label>
                                <p class="form-control-static mt-0">
                                    {{ object.percent_humidity_inf }} - {{ object.percent_humidity_sup }} %
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="mb-0">Detalle de la Condición</label>
                                <p class="form-control-static mt-0">{{ object.detail_condition|default:"Sin detalle" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ list_url }}" class="btn btn-default">
                        <i class="now-ui-icons arrows-1_minimal-left"></i> Volver
                    </a>
                    <a href="{% url 'condition:condition_update' object.pk %}" class="btn btn-warning">
                        <i class="now-ui-icons ui-2_settings-90"></i> Editar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/condition/templates/condition/list_condition.html
{% extends 'list_one.html' %} {% load static %} {% block head_list %}
<script src="{% static 'list_condition.js' %}"></script>
{% endblock %} {% block columns %}
<tr>
  <th class="text-center">Zona</th>
  <th class="text-center">Descripción</th>
  <th class="text-center">Tipo de Estudio</th>
  <th class="text-center">T° Inf / Sup</th>
  <th class="text-center">HR% Inf /Sup</th>
  <th class="text-center">Meses Estudio</th>
  <th class="text-center">Estado</th>
  <th class="text-center">Opciones</th>
</tr>
{% endblock %} {% block rows %} {% endblock %} {% block create %}
<a
  href="{{ create_url }}"
  class="btn btn-primary btn-round btn-icon float-end"
  style="margin-left: 10px"
>
  <i class="now-ui-icons ui-1_simple-add"></i>
</a>
{% endblock %} {% block javascript %} {% endblock %}