core/condition/urls.py
from django.urls import path
from core.condition.views import *

app_name = 'condition'

urlpatterns = [
    path('add/', ConditionCreateView.as_view(), name='condition_create'),
    path('list/', ConditionListView.as_view(), name='condition_list'),
    path('update/<uuid:pk>/', ConditionUpdateView.as_view(), name='condition_update'),
    path('detail/<uuid:pk>/', ConditionDetailView.as_view(), name='condition_detail'),
]

core/product/urls.py
from django.conf.urls.static import static
from django.urls import path

from studystb import settings
from core.product.views import *

app_name = 'product'

urlpatterns = [
    path('add/', ProductCreateView.as_view(), name='product_create'), 
    path('list/', ProductListView.as_view(), name='product_list'),    
    path('update/<uuid:pk>/', ProductUpdateView.as_view(), name='product_update'),    
    path('detail/<uuid:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.conf.urls.static import static
from django.urls import path

from studystb import settings
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<str:slug>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<str:slug>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<str:slug>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<str:slug>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<str:slug>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

studystb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from studystb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('product/', include('core.product.urls')),
    path('condition/', include('core.condition.urls')),
    path('protocol/', include('core.protocol.urls')),
    # path('company/', include('core.company.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!--

=========================================================
* Now UI Dashboard PRO - v1.6.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro
* Copyright 2021 Creative Tim (http://www.creative-tim.com)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>{{ title }}</title>
      <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {{ title }}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/css/now-ui-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/demo/demo.css' %}" rel="stylesheet" />
  <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
    {% block head %}
    	
    {% endblock %}
</head>

{% block body %}
	
{% endblock %}
<!--   Core JS Files   -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/moment.min.js' %}"></script>
<!--  Plugin for Sweet Alert -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/sweetalert2.min.js' %}"></script>
<!-- Forms Validations Plugin -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/jquery.validate.min.js' %}"></script>
<!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/bootstrap-selectpicker.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/bootstrap-datetimepicker.js' %}"></script>
<!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/jquery.dataTables.min.js' %}"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
<!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/fullcalendar.min.js' %}"></script>
<!-- Vector Mp plugin, full documentation here: http://jvectormap.com/documentation/ -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/jquery-jvectormap.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Google Maps Plugin    -->
{#<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>#}<!-- Chart JS -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/js/now-ui-dashboard.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/demo/demo.js' %}"></script>
{% block javascript %}
	
{% endblock %}
</html>

templates/body.html
{% extends 'base.html' %}


{% block body %}

    <body>
    <div class="wrapper">
    
        {% include 'sidebar.html' %}

        <div class="main-panel">

            {% include 'header.html' %}

            <div class="content">
                {% block content %}

                {% endblock %}
            </div>

            {% include 'footer.html' %}
        </div>
    </div>

    {#        <div class="modal fade" id="modal_template" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>#}
    {#        <div class="modal fade" id="delete" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>#}
    {#        <div class="modal fade" id="edition" role="dialog" aria-labelledby="modal" aria-hidden="true"></div>#}
    
    </body>

{% endblock %}


templates/footer.html
<footer class="footer">
            <div class="container-fluid">
                <nav>
                    <ul>
                        <li>
                            <a href="https://cieltechno.com" target="_blank">
                                CielTechno SAS
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>
                    , Desarrollado por <a href="https://cieltechno.com" target="_blank">CielTechno SAS</a>.
                </div>
            </div>
        </footer>

templates/form_one.html
{% extends 'body.html' %}


{% block content %}

    <div class="col-md-{{ div }}">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">{{ entity }}</h4>
            </div>
            <form enctype="multipart/form-data" method="post" action="" class="form-horizontal">
                <div class="card-body ">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="{{ action }}">
                    {% for field in form.visible_fields %}
                        {% if forloop.first %}
                            <div class="row">
                        {% endif %}
                    <div class="{% if field.field.col_class %}{{ field.field.col_class }}{% else %}col-md-4{% endif %}">
                        <div {% if field.name == 'photo' or field.name == 'companyLogo' or field.name == 'image_product' %}
                            class="fileinput fileinput-new text-center" data-provides="fileinput"
                        {% else %} class="form-group" {% endif %}>
                            {% if field.name == 'photo' or field.name == 'companyLogo' or field.name == 'image_product' %}
                                <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                <div>
                                        <span class="btn btn-rose btn-round btn-file">
                                            <span class="fileinput-new">Seleccionar imagen</span>
                                            <span class="fileinput-exists">Cambiar</span>
                                            {{ field }}
                                        </span>
                                    {% if field.help_text %}
                                        <sub>*{{ field.help_text }}</sub>
                                    {% endif %}
                                    <a href="#" class="btn btn-danger btn-round fileinput-exists"
                                       data-bs-dismiss="fileinput"><i class="fa fa-times"></i> Eliminar</a>
                                </div>
                            {% else %}
                                <label for=id_{{ field.name }}>
                                    {{ field.label }}{% if field.field.required %}*{% endif %}
                                </label>
                                {% if field.help_text %}
                                    <sub>*{{ field.help_text }}</sub>
                                {% endif %}
                                {{ field }}
                                </div>
                                </div>
                            {% endif %}
                    {% if forloop.last %}
                    {% elif forloop.counter|divisibleby:number_column %}
                        </div>
                        <div class="row">
                    {% endif %}
                    {% endfor %}
                    </div>
                    <div class="card-footer text-center">
                        <a href="{{ list_url }}" class="btn btn-danger">Cancelar</a>
                        <button type="submit" class="btn btn-success" id="btnSubmit">Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="application/javascript">
        var isSubmitting = false;
        
        $('form').on('submit', function (e) {
            e.preventDefault();
            
            // Prevenir múltiples envíos
            if (isSubmitting) {
                return false;
            }
            
            isSubmitting = true;
            var $btn = $('#btnSubmit');
            var originalText = $btn.html();
            
            // Mostrar spinner y deshabilitar botón
            $btn.prop("disabled", true);
            $btn.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Guardando...');
            
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
                // Restaurar botón en caso de error
                $btn.prop("disabled", false);
                $btn.html(originalText);
                isSubmitting = false;
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
                // Restaurar botón en caso de fallo
                $btn.prop("disabled", false);
                $btn.html(originalText);
                isSubmitting = false;
            }).always(function (data) {
            });
        });


    </script>
{% endblock %}







templates/header.html
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="#">Company</a>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navigation">       
            <ul class="navbar-nav">             
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                       data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="now-ui-icons location_world"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Some Actions</span>
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item mt-2">
                    <a class="nav-brand" href="{% url 'logout' %}">
                        <p><span class="d-md-block mt-0">Cerrar Sesión</span></p>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

<div class="panel-header panel-header-sm">
    
</div>

templates/list_one.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    {% block head_list %}

    {% endblock %}
    <style>
        #data {
            font-size: 13px;
        }

        #data thead th {
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .card-title {
            font-size: 1.5rem;
            font-weight: bold;
        }

        .dataTables_length label,
        .dataTables_filter label,
        .dataTables_info,
        .dataTables_paginate {
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-md-{{ div }}">
                {% if messages %}
                    {% for message in messages %}
                        <div id="message" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                                <i class="now-ui-icons ui-1_simple-remove"></i>
                            </button>
                            <span>{{ message }}</span>
                        </div>
                        <br>                      
                    {% endfor %}
                {% endif %}
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" style="display: inline-flex">{{ entity }}</h4>
                        {% block create %}

                        {% endblock %}
                    </div>
                    <div class="card-body">
                        <table id="data" class="table table-striped table-bordered"
                               style="border-collapse: separate; border-spacing: 0; width: 100%">
                            <thead>
                            {% block columns %}

                            {% endblock %}
                            </thead>
                            <tfoot>
                            {% block columns_foot %}

                            {% endblock %}
                            </tfoot>
                            <tbody>
                            {% block rows %}

                            {% endblock %}
                            </tbody>
                        </table>
                    </div><!-- end content-->
                </div><!--  end card  -->
            </div> <!-- end col-md-12 -->
        </div> <!-- end row -->
    </div>
{% endblock %}

{% block javascript %}
    <!-- datatable list -->
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false,
                paging: true,
                searching: true,
                language: {
                    url: "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
                },
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                });
            });
        });
    </script>
{% endblock %}

templates/sidebar.html
{% load static %}

<div class="sidebar" data-color="orange">
  <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"
  
        Tip 2: you can also add an image using data-image tag
        -->

  <div class="logo">
    <a href="#" class="simple-text logo-mini"> AE </a>

    <a href="#" class="simple-text logo-normal"> Arrhenius Estudio </a>
    <div class="navbar-minimize">
      <button
        id="minimizeSidebar"
        class="btn btn-simple btn-icon btn-neutral btn-round"
      >
        <i
          class="now-ui-icons text_align-center visible-on-sidebar-regular"
        ></i>
        <i
          class="now-ui-icons design_bullet-list-67 visible-on-sidebar-mini"
        ></i>
      </button>
    </div>
  </div>

  <div class="sidebar-wrapper">
    <div class="user">
      <div class="photo">
        <img
          src="{{ request.user.get_image }}"
          alt="{{ request.user.get_full_name }}"
        />
      </div>
      <div class="info">
        <a data-bs-toggle="collapse" href="#collapseExample" class="collapsed">
          <span>
            {{ request.user.get_full_name }}
            <b class="caret"></b>
          </span>
        </a>
        <div class="clearfix"></div>
        <div class="collapse" id="collapseExample">
          <ul class="nav">
            <li>
              <a href="{% url 'user:user_profile' request.user.slug %}">
                <span class="sidebar-mini-icon">MP</span>
                <span class="sidebar-normal">Mi Perfil</span>
              </a>
            </li>
            <li>
              <a href="{% url 'user:user_profile_update' request.user.slug %}">
                <span class="sidebar-mini-icon">EP</span>
                <span class="sidebar-normal">Editar Perfil</span>
              </a>
            </li>
            <li>
              <a href="{% url 'user:change_password' %}">
                <span class="sidebar-mini-icon">CP</span>
                <span class="sidebar-normal">Cambiar Contraseña</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <ul class="nav">
      {% url 'product:product_list' as product_list %} 
      {% url 'product:product_create' as product_create %}

      <li
        class="{% if product_list in request.path or product_create in request.path %}active{% endif %}"
      >
        <a href="{% url 'product:product_list' %}">
          <i class="now-ui-icons design_app"></i>
          <p>Productos</p>
        </a>
      </li>

      {% url 'condition:condition_list' as condition_list %} 
      {% url 'condition:condition_create' as condition_create %}
      <li
        class="{% if condition_list in request.path or condition_create in request.path %}active{% endif %}"
      >
        <a href="{% url 'condition:condition_list' %}">
          <i class="now-ui-icons education_paper"></i>
          <p>Condiciones</p>
        </a>
      </li>
      {% url 'user:user_list' as user_list %} 
      {% url 'user:user_create' as user_create %}

      <li
        class="{% if user_list in request.path or user_create in request.path or '/user/update/' in request.path or '/user/detail/' in request.path or '/user/update-password/' in request.path %}active{% endif %}"
      >
        <a data-bs-toggle="collapse" href="#config">
          <i class="now-ui-icons ui-1_settings-gear-63"></i>
          <p>
            Configuración
            <b class="caret"></b>
          </p>
        </a>

        <div
          class="{% if user_list in request.path or user_create in request.path or '/user/update/' in request.path or '/user/detail/' in request.path or '/user/update-password/' in request.path %}collapse show{% else %}collapse{% endif %}"
          id="config"
        >
          <ul class="nav">
            <li
              class="{% if user_list in request.path or user_create in request.path or '/user/update/' in request.path or '/user/detail/' in request.path or '/user/update-password/' in request.path %}active{% endif %}"
            >
              <a href="{% url 'user:user_list' %}">
                <span class="sidebar-mini-icon">US</span>
                <span class="sidebar-normal">Usuarios</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="sidebar-mini-icon">C2</span>
                <span class="sidebar-normal">Collapse 2</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>