core/user/urls.py
from django.conf.urls.static import static
from django.urls import path

from studystb import settings
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<str:slug>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<str:slug>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<str:slug>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<str:slug>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<str:slug>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

studystb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from studystb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('product/', include('core.product.urls')),
    path('condition/', include('core.condition.urls')),
    path('protocol/', include('core.protocol.urls')),
    # path('company/', include('core.company.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/models.py
import os
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import localtime

from studystb.settings import MEDIA_URL, STATIC_URL


def validator_file_image(value):
    limit = 256 * 1024     # de bits
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.jpeg', '.jpg', '.png', '.svg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Subir imagenes solamente con extensión .jpg, .png o .svg y tamaño máximo de 256Kb')
    if value.size > limit:
        raise ValidationError('Archivo demasiado grande. El tamaño no debe exceder los 256Kb.')


# Usuarios
class User(AbstractUser):
    cedula = models.CharField(max_length=15, null=True, blank=True, unique=False, verbose_name='Cédula')
    cargo = models.CharField(max_length=50, null=True, blank=True, verbose_name='Cargo')
    email_person = models.EmailField(null=True, blank=True, verbose_name='Email Personal')
    cellphone = models.CharField(max_length=10, null=True, blank=True, verbose_name='N° Celular')
    address_user = models.CharField(max_length=50, null=True, blank=True, verbose_name='Dirección')
    date_birth = models.DateField(null=True, blank=True, verbose_name='Fecha de Nacimiento')
    photo = models.ImageField(
        upload_to='user/%Y%m%d', null=True, blank=True, verbose_name='Foto', validators=[validator_file_image])
    slug = models.SlugField(unique=True, null=False, blank=False)

    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)
        self.original_password = self.password

    def __str__(self):
        return str(self.get_full_name()) + ', ' + str(self.cargo)

    def get_image(self):
        if self.photo:
            return '{}{}'.format(MEDIA_URL, self.photo)
        return '{}{}'.format(STATIC_URL, 'img/default-avatar.png')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(uuid.uuid4()))
        if self.username is not int:
            self.username = self.username.lower()
        if self.id:
            if self._password_has_been_changed():
                PasswordHistoryUser.remember_password(self)
        super().save(*args, **kwargs)

    def _password_has_been_changed(self):
        return self.original_password != self.password


# Histórico de Contraseñas utilizadas
class PasswordHistoryUser(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    old_pass = models.CharField(max_length=128)
    pass_date = models.DateTimeField()

    @classmethod
    def remember_password(cls, user):
        if user:
            cls(username=user, old_pass=user.password, pass_date=localtime()).save()

core/user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, DetailView, FormView

from core.mixins import ValidatePermissionRequiredMixin
from core.user.forms import *
from core.user.models import User


# Creación de usuario
class UserCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.add_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        context['div'] = '12'
        context['entity'] = 'Creación de Usuario'
        context['number_column'] = 3
        return context


# Listado de usuarios
class UserListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = User
    template_name = 'list_user.html'
    permission_required = 'user.add_user'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                usuarios = list(User.objects.values(
                    'id',
                    'cedula',
                    'username',
                    'cargo',
                    'groups__name',
                    'email',
                    'is_active',
                    'first_name',
                    'last_name',
                    'slug'
                ).filter(is_superuser=False).order_by('first_name'))
                return JsonResponse(usuarios, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Usuarios'
        context['create_url'] = reverse_lazy('user:user_create')
        context['entity'] = 'Usuarios'
        context['div'] = '12'
        return context


# Edición de usuario por Administrador
class UserUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'update_user.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Usuarios'
        context['list_url'] = self.success_url
        context['entity'] = 'Editar Usuario'
        context['action'] = 'edit'
        context['users'] = User.objects.all()
        return context


# Detalle de Usuario por administrador
class UserDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = User
    template_name = 'detail_user.html'
    permission_required = 'user.change_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(UserDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Perfil de Usuario'
        context['entity'] = 'Perfil de Usuario'
        context['group_user'] = User.objects.values('groups__name').filter(slug=self.kwargs['slug'])
        return context


# Detalle de Perfil de usuario logueado
class MyProfileDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = User
    template_name = 'detail.html'
    permission_required = 'user.view_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(MyProfileDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mi Perfil'
        context['entity'] = 'Mi Perfil'
        return context


# Edición de perfil por usuario logueado
class ProfileUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUpdateForm
    template_name = 'update_user.html'
    success_url = reverse_lazy('start:start')
    permission_required = 'user.view_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Su perfil ha sido actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Perfil'
        context['list_url'] = reverse_lazy('user:user_profile', kwargs={'slug': self.kwargs.get('slug')})
        context['entity'] = 'Editar Perfil'
        context['action'] = 'edit'
        return context


# Reseteo de contraseña por administrador
class UserPasswordUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserPasswordUpdateForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    messages.success(request, f'Contraseña de usuario reseteada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reseteo de Contraseña'
        context['list_url'] = self.success_url
        context['entity'] = 'Reseteo de Contraseña de Usuario'
        context['action'] = 'edit'
        return context


# Cambio de contraseña por usuario
class UserChangePasswordView(LoginRequiredMixin, ValidatePermissionRequiredMixin, FormView):

core/user/templates/create_user.html
{% extends 'form_one.html' %}

core/user/templates/detail.html
{% extends 'body.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ entity }}</h5>
                </div>
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="mb-0">Usuario</label>
                                    <p class="form-control-static mt-0">{{ object.username }}</p>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="mb-0">Cédula</label>
                                    <p class="form-control-static mt-0">{{ object.cedula|default:"N/A" }}</p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="mb-0">Cargo</label>
                                    <p class="form-control-static mt-0">{{ object.cargo|default:"Sin cargo" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Nombre</label>
                                    <p class="form-control-static mt-0">{{ object.first_name }}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Apellido</label>
                                    <p class="form-control-static mt-0">{{ object.last_name }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Email Corporativo</label>
                                    <p class="form-control-static mt-0">{{ object.email }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Email Personal</label>
                                    <p class="form-control-static mt-0">{{ object.email_person|default:"N/A" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="mb-0">Celular</label>
                                    <p class="form-control-static mt-0">{{ object.cellphone|default:"N/A" }}</p>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="mb-0">Dirección</label>
                                    <p class="form-control-static mt-0">{{ object.address_user|default:"N/A" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Fecha de Nacimiento</label>
                                    <p class="form-control-static mt-0">{{ object.date_birth|date:"d/m/Y"|default:"N/A" }}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'user:user_profile_update' object.slug %}" class="btn btn-warning">
                        <i class="now-ui-icons ui-2_settings-90"></i> Editar Perfil
                    </a>
                    <a href="{% url 'user:change_password' %}" class="btn btn-success">
                        <i class="now-ui-icons objects_key-25"></i> Cambiar Contraseña
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/img/bg5.jpg' %}" alt="...">
                </div>
                <div class="card-body">
                    <div class="author">
                        <a href="javascript:void(0)">
                            <img class="avatar border-gray" src="{{ object.get_image }}" alt="...">
                            <h5 class="title">{{ object.get_full_name }}</h5>
                        </a>
                        <p class="description">
                            {{ object.cargo|default:"Sin cargo asignado" }}
                        </p>
                    </div>
                    <p class="description text-center">
                        {{ object.email }}
                        <br>
                        {% if object.email_person %}
                            <small>{{ object.email_person }}</small>
                        {% endif %}
                    </p>
                </div>
                <div class="card-footer">
                    <hr>
                    <div class="button-container">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-6 ms-auto">
                                <h5>{{ object.username }}
                                    <br>
                                    <small>Usuario</small>
                                </h5>
                            </div>
                            <div class="col-lg-6 col-md-6 col-6 ms-auto me-auto">
                                <h5>
                                    {% if object.cellphone %}
                                        {{ object.cellphone }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                    <br>
                                    <small>Celular</small>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/user/templates/detail_user.html
{% extends 'body.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Editar Perfil</h5>
                </div>
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="mb-0">Usuario</label>
                                    <p class="form-control-static mt-0">{{ object.username }}</p>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="mb-0">Cédula</label>
                                    <p class="form-control-static mt-0">{{ object.cedula|default:"N/A" }}</p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="mb-0">Cargo</label>
                                    <p class="form-control-static mt-0">{{ object.cargo|default:"Sin cargo" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Nombre</label>
                                    <p class="form-control-static mt-0">{{ object.first_name }}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Apellido</label>
                                    <p class="form-control-static mt-0">{{ object.last_name }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Email Corporativo</label>
                                    <p class="form-control-static mt-0">{{ object.email }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Email Personal</label>
                                    <p class="form-control-static mt-0">{{ object.email_person|default:"N/A" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="mb-0">Celular</label>
                                    <p class="form-control-static mt-0">{{ object.cellphone|default:"N/A" }}</p>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="mb-0">Dirección</label>
                                    <p class="form-control-static mt-0">{{ object.address_user|default:"N/A" }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Fecha de Nacimiento</label>
                                    <p class="form-control-static mt-0">{{ object.date_birth|date:"d/m/Y"|default:"N/A" }}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="mb-0">Rol</label>
                                    <p class="form-control-static mt-0">
                                        {% for group in group_user %}
                                            <span class="badge badge-primary">{{ group.groups__name }}</span>
                                        {% endfor %}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="mb-0">Estado</label>
                                    <p class="form-control-static mt-0">
                                        {% if object.is_active %}
                                            <span class="badge badge-success">Activo</span>
                                        {% else %}
                                            <span class="badge badge-danger">Inactivo</span>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'user:user_list' %}" class="btn btn-default">
                        <i class="now-ui-icons arrows-1_minimal-left"></i> Volver
                    </a>
                    <a href="{% url 'user:user_update' object.slug %}" class="btn btn-warning">
                        <i class="now-ui-icons ui-2_settings-90"></i> Editar
                    </a>
                    <a href="{% url 'user:user_password_update' object.slug %}" class="btn btn-success">
                        <i class="now-ui-icons objects_key-25"></i> Resetear Contraseña
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img src="{% static 'lib/now-ui-dashboard-pro-v1.6.0/assets/img/bg5.jpg' %}" alt="...">
                </div>
                <div class="card-body">
                    <div class="author">
                        <a href="javascript:void(0)">
                            <img class="avatar border-gray" src="{{ object.get_image }}" alt="...">
                            <h5 class="title">{{ object.get_full_name }}</h5>
                        </a>
                        <p class="description">
                            {{ object.cargo|default:"Sin cargo asignado" }}
                        </p>
                    </div>
                    <p class="description text-center">
                        {{ object.email }}
                    </p>
                </div>
                <div class="card-footer">
                    <hr>
                    <div class="button-container">
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-6 ms-auto">
                                <h5>{{ object.username }}
                                    <br>
                                    <small>Usuario</small>
                                </h5>
                            </div>
                            <div class="col-lg-4 col-md-6 col-6 ms-auto me-auto">
                                <h5>
                                    {% if object.is_active %}
                                        <i class="now-ui-icons ui-1_check text-success"></i>
                                    {% else %}
                                        <i class="now-ui-icons ui-1_simple-remove text-danger"></i>
                                    {% endif %}
                                    <br>
                                    <small>Estado</small>
                                </h5>
                            </div>
                            <div class="col-lg-4 me-auto">
                                <h5>
                                    {% for group in group_user %}
                                        {{ group.groups__name|truncatechars:10 }}
                                    {% endfor %}
                                    <br>
                                    <small>Rol</small>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}